server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/trusta}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inspection-service-centers
              uri: lb://inspection-service
              predicates:
                - Path=/api/v1/centers/**

            - id: inspection-service-inspections
              uri: lb://inspection-service
              predicates:
                - Path=/api/v1/inspections/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**, /api/v1/reports/**

            - id: user-service-admin
              uri: lb://user-service
              predicates:
                - Path=/api/v1/admin/users/**, /api/v1/admin/reports/**, /api/v1/admin/accounts/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: order-service-admin
              uri: lb://order-service
              predicates:
                - Path=/api/v1/admin/orders/**

            - id: wallet-service
              uri: lb://wallet-service
              predicates:
                - Path=/api/v1/wallets/**

            - id: wallet-service
              uri: lb://wallet-service
              predicates:
                - Path=/api/v1/wallets/**

          default-filters:
            - AddResponseHeader=X-Gateway, trusta-market

          discovery:
            locator:
              enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      access: unrestricted